### ISSUE TITLE
import failed

### ISSUE THREAD

**Issue by RYG81** [ZHO-ZHO-ZHO/ComfyUI-DepthFM#1]
hi
Traceback (most recent call last):
  File "D:\000AI\ComfyUI\ComfyUI\nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\000AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-DepthFM\__init__.py", line 1, in <module>
    from . import DepthFM
  File "D:\000AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-DepthFM\DepthFM.py", line 6, in <module>
    from .depthfm import DepthFM
  File "D:\000AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-DepthFM\depthfm\__init__.py", line 4, in <module>
    from dfm import DepthFM
  File "D:\000AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-DepthFM\depthfm\dfm.py", line 9, in <module>
    from unet import UNetModel
  File "D:\000AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-DepthFM\depthfm\unet\__init__.py", line 4, in <module>
    from openaimodel import UNetModel
  File "D:\000AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-DepthFM\depthfm\unet\openaimodel.py", line 8, in <module>
    from util import (
ImportError: cannot import name 'checkpoint' from 'util' (D:\000AI\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\util.py)

Cannot import D:\000AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-DepthFM module for custom nodes: cannot import name 'checkpoint' from 'util' (D:\000AI\ComfyUI\Com
fyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\util.py)

import failing

**Comment by supwang** [comment]
me too

**Comment by zhenyuanzhou** [comment]
same

**Comment by YanWenKun** [comment]
我这里也是和 `comfyui_controlnet_aux` 的  `util` 命名空间冲突了

**Comment by supwang** [comment]
工作流是不错，但作者好像从来不回复任何问题，只管发布，不管答疑。@_@

**Comment by supwang** [comment]
按照上面的方法修改了文件，报错依旧。

Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DepthFM\__init__.py", line 1, in <module>
    from . import DepthFM
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DepthFM\DepthFM.py", line 6, in <module>
    from .depthfm import DepthFM
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DepthFM\depthfm\__init__.py", line 4, in <module>
    from .dfm import DepthFM
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DepthFM\depthfm\dfm.py", line 10, in <module>
    from diffusers import AutoencoderKL
ModuleNotFoundError: No module named 'diffusers'

Cannot import D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DepthFM module for custom nodes: No module named 'diffusers'

并且：
DepthFM_ModelLoader_Zho和DepthFM_Zho哪里都找不到可以下载的地方。

**Comment by Tobe2d** [comment]
this developer never reply

**Comment by YanWenKun** [comment]
> 按照上面的方法修改了文件，报错依旧。
> ModuleNotFoundError: No module named 'diffusers'

@supwang 你的环境缺少 `diffusers` 这个包，用 ComfyUI-Manager 的尝试修复（try fix）试试

**Comment by supwang** [comment]
> > 按照上面的方法修改了文件，报错依旧。
> > ModuleNotFoundError: No module named 'diffusers'
> 
> @supwang 你的环境缺少 `diffusers` 这个包，用 ComfyUI-Manager 的尝试修复（try fix）试试

谢谢，节点都搞定了，但在生成图片是遇到下面这个问题，请问有解吗？
Error occurred when executing DepthFM_Zho:

Allocation on device 0 would exceed allowed memory. (out of memory)
Currently allocated : 19.92 GiB
Requested : 16.00 GiB
Device limit : 23.99 GiB
Free (according to CUDA): 0 bytes
PyTorch limit (set by user-supplied memory fraction)
: 17179869184.00 GiB

File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DepthFM\DepthFM.py", line 65, in df_image
depth = model.predict_depth(img_tensor, num_steps=steps, ensemble_size=ensemble_size)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DepthFM\depthfm\dfm.py", line 97, in predict_depth
return self.forward(ims, num_steps, ensemble_size)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DepthFM\depthfm\dfm.py", line 81, in forward
depth_z = self.generate(x_source, num_steps=num_steps, context=context, context_ca=conditioning)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DepthFM\depthfm\dfm.py", line 51, in generate
ode_results = odeint(ode_fn, z, t, **ode_kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torchdiffeq\_impl\odeint.py", line 77, in odeint
solution = solver.integrate(t)
^^^^^^^^^^^^^^^^^^^
File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torchdiffeq\_impl\solvers.py", line 105, in integrate
dy, f0 = self._step_func(self.func, t0, dt, t1, y0)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torchdiffeq\_impl\fixed_grid.py", line 10, in _step_func
f0 = func(t0, y0, perturb=Perturb.NEXT if self.perturb else Perturb.NONE)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
return forward_call(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torchdiffeq\_impl\misc.py", line 189, in forward
return self.base_func(t, y)
^^^^^^^^^^^^^^^^^^^^
File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DepthFM\depthfm\dfm.py", line 34, in ode_fn
return self.model(x=x, t=t, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
return forward_call(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DepthFM\depthfm\unet\openaimodel.py", line 837, in forward
h = module(h, emb, context_ca)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
return forward_call(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DepthFM\depthfm\unet\openaimodel.py", line 85, in forward
x = layer(x, context)
^^^^^^^^^^^^^^^^^
File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
return forward_call(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DepthFM\depthfm\unet\attention.py", line 368, in forward
x = block(x, context=context[i])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
return forward_call(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DepthFM\depthfm\unet\attention.py", line 282, in forward
return checkpoint(
^^^^^^^^^^^
File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DepthFM\depthfm\unet\util.py", line 39, in checkpoint
return func(*inputs)
^^^^^^^^^^^^^
File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DepthFM\depthfm\unet\attention.py", line 288, in _forward
self.attn1(
File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
return forward_call(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DepthFM\depthfm\unet\attention.py", line 176, in forward
out = F.scaled_dot_product_attention(q, k, v, scale=(math.log(n_tokens) / math.log(n_tokens*4) / self.dim_head)**0.5 if is_self_attention else None)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by YanWenKun** [comment]
> 谢谢，节点都搞定了，但在生成图片是遇到下面这个问题，请问有解吗？ Error occurred when executing DepthFM_Zho:
> 
> Allocation on device 0 would exceed allowed memory. (out of memory) Currently allocated : 19.92 GiB Requested : 16.00 GiB Device limit : 23.99 GiB Free (according to CUDA): 0 bytes PyTorch limit (set by user-supplied memory fraction) : 17179869184.00 GiB
> 

@supwang 你这是显存不够了，而且超了很多（提示已分配 19.92 GiB ，此次请求 16.00 GiB ）。可能参数哪里不对，照理说深度预测不需要这么大显存的

**Comment by supwang** [comment]
> > 谢谢，节点都搞定了，但在生成图片是遇到下面这个问题，请问有解吗？ Error occurred when executing DepthFM_Zho:
> > Allocation on device 0 would exceed allowed memory. (out of memory) Currently allocated : 19.92 GiB Requested : 16.00 GiB Device limit : 23.99 GiB Free (according to CUDA): 0 bytes PyTorch limit (set by user-supplied memory fraction) : 17179869184.00 GiB
> 
> @supwang 你这是显存不够了，而且超了很多（提示已分配 19.92 GiB ，此次请求 16.00 GiB ）。可能参数哪里不对，照理说深度预测不需要这么大显存的

显存应该是不会不够的，两台电脑都是这个报错，不知道具体哪里出问题了。

**Comment by CavinHuang** [comment]
我也是一样的错误：

!!! Exception during processing!!! Allocation on device
Traceback (most recent call last):
  File "D:\workspace\projects\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\workspace\projects\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\workspace\projects\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\workspace\projects\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-depth-fm\nodes.py", line 81, in process
    sub_images = self.model.predict_depth(images[start_idx:start_idx+per_batch], num_steps=steps, ensemble_size=ensemble_size)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\workspace\projects\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\workspace\projects\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-depth-fm\depthfm\dfm.py", line 117, in predict_depth
    return self.forward(ims, num_steps, ensemble_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\workspace\projects\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-depth-fm\depthfm\dfm.py", line 97, in forward
    depth_z = self.generate(x_source, num_steps=num_steps, context=context, context_ca=conditioning)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\workspace\projects\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-depth-fm\depthfm\dfm.py", line 64, in generate
    ode_results = odeint(ode_fn, z, t, **ode_kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\workspace\projects\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torchdiffeq\_impl\odeint.py", line 79, in odeint
    solution = solver.integrate(t)
               ^^^^^^^^^^^^^^^^^^^
  File "D:\workspace\projects\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torchdiffeq\_impl\solvers.py", line 114, in integrate
    dy, f0 = self._step_func(self.func, t0, dt, t1, y0)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\workspace\projects\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torchdiffeq\_impl\fixed_grid.py", line 10, in _step_func
    f0 = func(t0, y0, perturb=Perturb.NEXT if self.perturb else Perturb.NONE)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\workspace\projects\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\workspace\projects\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\workspace\projects\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torchdiffeq\_impl\misc.py", line 197, in forward
    return self.base_func(t, y)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\workspace\projects\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-depth-fm\depthfm\dfm.py", line 47, in ode_fn
    return self.model(x=x, t=t, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\workspace\projects\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\workspace\projects\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\workspace\projects\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-depth-fm\depthfm\unet\openaimodel.py", line 837, in forward
    h = module(h, emb, context_ca)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\workspace\projects\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\workspace\projects\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\workspace\projects\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-depth-fm\depthfm\unet\openaimodel.py", line 85, in forward
    x = layer(x, context)
        ^^^^^^^^^^^^^^^^^
  File "D:\workspace\projects\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\workspace\projects\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\workspace\projects\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-depth-fm\depthfm\unet\attention.py", line 371, in forward
    x = block(x, context=context[i])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\workspace\projects\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\workspace\projects\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\workspace\projects\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-depth-fm\depthfm\unet\attention.py", line 285, in forward
    return checkpoint(
           ^^^^^^^^^^^
  File "D:\workspace\projects\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-depth-fm\depthfm\unet\util.py", line 39, in checkpoint
    return func(*inputs)
           ^^^^^^^^^^^^^
  File "D:\workspace\projects\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-depth-fm\depthfm\unet\attention.py", line 291, in _forward
    self.attn1(
  File "D:\workspace\projects\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\workspace\projects\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\workspace\projects\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-depth-fm\depthfm\unet\attention.py", line 179, in forward
    out = F.scaled_dot_product_attention(q, k, v, scale=(math.log(n_tokens) / math.log(n_tokens*4) / self.dim_head)**0.5 if is_self_attention else None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: Allocation on device

Prompt executed in 14.35 seconds
